publish: false
delivery:
  rbac:
    rolebindings:
      - role: cr_admin_pipes
        name: adminpipe
        subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_pr_adminpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_adminallpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_adminallpipe
      - role: cr_operator_pipes
        name: operatorpipe
        subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_pr_operatorpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_operatorallpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_operatorallpipe
      - role: cr_read_rerun_PLR
        name: readrerunPLR
        subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_pr_readrerunpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_rubygems_readrerunallpipe
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: g_hq_readrerunallpipe
